language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
  - julia: nightly
notifications:
    email: false
coveralls: false
